unit Test.Model.Leitor;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Model.Leitor.OCP, Model.Arquivo.Txt.OCP, Model.Arquivo.CSV.OCP, Model.Dados.OCP;

type
  // Test methods for class TLeitor

  TestTLeitor = class(TTestCase)
  strict private
  private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestarLeituraDoArquivoTxt;
    procedure TestarLeituraDoArquivoCSV;
  end;

implementation

procedure TestTLeitor.SetUp;
begin

end;

procedure TestTLeitor.TearDown;
begin
  
end;

procedure TestTLeitor.TestarLeituraDoArquivoTxt();
var
  lLeitor: TLeitor;
  lDados: IDados;
begin
  lLeitor := TLeitor.Create('../Arquivos', 'dados.txt');
  try
    lLeitor.LerArquivo(TTxt.Create());


    CheckEquals(4, lLeitor.ListaDeDados.Count, 'A quatidade de dados extraídos não está correta');
    CheckTrue(lLeitor.ListaDeDados.TryGetValue('35495984080' ,lDados), 'CPF não foi encontrado na lista');
    CheckEquals('Gustavo Santos', lDados.Nome);

  finally
    lLeitor.Free;
  end;
end;

procedure TestTLeitor.TestarLeituraDoArquivoCSV();
var
  lLeitor: TLeitor;
  lDados: IDados;
begin
  lLeitor := TLeitor.Create('../Arquivos', 'dados.csv');
  try
    lLeitor.LerArquivo(TCSV.Create());


    CheckEquals(4, lLeitor.ListaDeDados.Count, 'A quatidade de dados extraídos não está correta');
    CheckTrue(lLeitor.ListaDeDados.TryGetValue('405.986.210-08' ,lDados), 'CPF não foi encontrado na lista');
    CheckEquals('Fernanda Silva', lDados.Nome);

  finally
    lLeitor.Free;
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTLeitor.Suite);
end.

